[package]
name = "weird_file_system"
version = "0.1.1"
edition = "2024"
author = "Cyclic"
repository = "https://github.com/Cyclic007/WFS"
description = "A fun weird fuse filesystem"
readme = "README.md"
license = "Apache-2.0"

[dependencies]
fuse_mt = "0.6.4"
lazy_static = "1.5.0"
libc = "0.2.189"
log = "0.4.34"
sys-mount = "3.1.0"
